version: '3'

networks:
  www:
    external:
      name: www

services:
  node:
    image: "node:12"
    env_file:
      - .env
    volumes:
      - .:/app:cached
      - ./node_modules:/app/node_modules:delegated
      - ./.next:/app/.next:delegated
      - ./out:/app/out:delegated
    ports:
      - "3000:3000"
    working_dir: /app
    networks:
      - www
      - default
    command: sh -c "npm install && npm run dev"
