# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# TODO: https://github.com/ad-m/github-push-action

name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        
      - name: NPM Install
        run: npm ci --only=production
        
      - name: Next.js build and export
        run: npm run build && npm run export
        env:
          APP_NAME: ${{ secrets.APP_NAME }}
          API_HOST: ${{ secrets.API_HOST }}
          CACHE_HOST: ${{ secrets.CACHE_HOST }}
          OSM_HOST: ${{ secrets.OSM_HOST }}
          TF_API_KEY: ${{ secrets.TF_API_KEY }}
        
      - name: Git Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          BRANCH: gh-pages
          FOLDER: out
          CLEAN: true
