# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# TODO: https://github.com/ad-m/github-push-action

name: Build

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout main
              uses: actions/checkout@v2

            - name: Node
              uses: actions/setup-node@v4
              with:
                  node-version: 16

            - name: NPM Install
              run: npm ci --only=production

            - name: Next.js build and export
              run: npm run build && npm run export
              env:
                  SECRETS_JSON: ${{ toJSON(secrets) }}

            - name: Git Deploy
              uses: JamesIves/github-pages-deploy-action@releases/v3
              with:
                  BRANCH: gh-pages
                  FOLDER: out
                  CLEAN: false
